import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import * as CryptoJS from 'crypto-js'

const Home: NextPage = () => {

  const service = async (dataSet: any) => {
    const response = await fetch('http://localhost:8000/decrypt', {
      method: 'POST', // *GET, POST, PUT, DELETE, etc.
      mode: 'cors', // no-cors, *cors, same-origin
      cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
      credentials: 'same-origin', // include, *same-origin, omit
      headers: {
        'Content-Type': 'application/json'
        // 'Content-Type': 'application/x-www-form-urlencoded',
      },
      redirect: 'follow', // manual, *follow, error
      referrerPolicy: 'no-referrer', // no-referrer, *no-referrer-when-downgrade, origin, origin-when-cross-origin, same-origin, strict-origin, strict-origin-when-cross-origin, unsafe-url
      body: JSON.stringify(dataSet) // body data type must match "Content-Type" header
    });
    return response.json()
  }

  const callService = async () => {
    const dataSet = {
      "id": 1,
      "content": "example-content"
    }
    const encrypt = CryptoJS.AES.encrypt(JSON.stringify(dataSet), 'secret key 123').toString()
    const res = await service({ data: encrypt })
    console.log('response', res)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={() => callService()}>btn</button>
    </div>
  )
}

export default Home
